In [1]:
from __future__ import division, print_function, absolute_import
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

ethnea_df = pd.read_csv('names_ethnea_genni_country_sample.csv')
ethnea_df

,AUID,Last,First,Ethnea,Genni,PubCountry
0,12872768_1,_Filho_,_Elias_Abdalla_,HISPANIC,M,Brazil
1,12565879_3,_Bou_Abdallah_,_Jad_,ARAB,M,France
2,17569133_1,_Abdel_Aziz_,_Ayman_,ARAB,M,USA
3,11213157_2,_Abdelmoula_,_Salma_,ARAB,F,Tunisia
4,11439058_1,_Abdou_,_Ibrahim_,ARAB,M,Egypt
5,10919608_3,_Abou_El_Fettouh_,_Hazem_,ARAB,M,USA
6,17314740_3,_Aboutaam_,_Rola_,ARAB,F,France
7,16564217_2,_Alvim_de_Abreu_Silva_Rodrigues_,_Aida_Alexandra_,HISPANIC,F,Brazil
8,6339395_2,_Cristina_Affonso_Scaletsky_,_Isabel_,HISPANIC,F,Brazil
9,7796089_2,_Agbenyega_,_Tsiri_,AFRICAN,-,Ghana
10,5473023_2,_Maria_Aguado_Garcia_,_Jose_,HISPANIC,M,Spain
11,15153355_4,_Aguilar_Guisado_,_Manuela_,HISPANIC,F,Spain
12,11981185_4,_Aguillon_Luna_,_Arturo_,HISPANIC,M,USA
13,12554913_2,_Ahmadzadeh_,_Ali_,ARAB,M,Iran
14,10066026_5,_Ibrahim_,_Ahmed_,ARAB,M,UnitedArabEmirates
15,17642770_2,_Letaief_,_Ahmed_,ARAB,M,Tunisia
16,14766995_2,_Shakeel_Ahmed_,_Mohammed_,ARAB,M,USA
17,16343417_1,_Aksoy_Dogan_,_Alev_,TURKISH,F,Turkey
18,3866040_3,_Nakatsukasa_Akune_,_Mitsumi_,JAPANESE,-,Japan
19,12663244_3,_Akyuz_,_Filiz_,TURKISH,F,Turkey
20,2830628_1,_Al_Gohary_,_Omaimah_,ARAB,F,SaudiArabia
21,12113661_3,_Al_Jedah_,_Jassim_,ARAB,M,Qatar
22,3104205_7,_Al_Khatib_,_Shadi_,ARAB,-,India
23,7520609_3,_Al_Najjar_,_Azmi_,ARAB,M,France
24,927746_1,_Alba_Conejo_,_Emilio_,HISPANIC,M,Spain
25,18451155_4,_Llaguno_,_Sheila_Alcantara_,HISPANIC,F,USA
26,9431676_4,_Alcocer_,_Marcos_,HISPANIC,M,UK
27,3720520_1,_Grazia_Alessandri_,_Maria_,ITALIAN,F,Italy
28,10480445_2,_Ali_Labib_,_Randa_,ARAB,F,Egypt
29,12636048_1,_Allie_Hamdulay_,_Shameez_,AFRICAN,-,SouthAfrica
...,...,...,...,...,...,...
44537,12641914_1,_Liu_,_Zhihong_,CHINESE,-,China
44538,16892144_4,_Liu_,_Zhen_ying_,CHINESE,-,China
44539,15566960_5,_Liu_,_Zhu_,CHINESE,-,China
44540,12828461_3,_Liu_,_Zhengjie_,CHINESE,-,USA
44541,12726928_3,_Liu_,_Zhengchun_,CHINESE,-,China
44542,17802886_5,_Liu_,_Ziliang_,CHINESE,-,China
44543,18032929_3,_Liu_,_Zhe_,CHINESE,-,China
44544,16690641_1,_Liu_,_Zulian_,CHINESE,-,UK
44545,17554931_2,_Liu_,_Zun_chun_,CHINESE,-,China
44546,18975769_5,_Liu_,_Ze_zhou_,CHINESE,-,China
44547,19458823_2,_Liu_,_Zhaochun_,CHINESE,-,China
44548,8734067_3,_Liu_,_ziying_,CHINESE,M,USA
44549,9706530_4,_Liu_,_zhenyu_,CHINESE,M,China
44550,6068528_4,_Tanaka_,_kenzo_,JAPANESE,M,Japan
44551,180046_3,_Tanaka_,_kimiko_,JAPANESE,F,USA
44552,1942669_3,_Tanaka_,_kazuhiro_,JAPANESE,M,Japan
44553,9571188_3,_Tanaka_,_koji_,JAPANESE,M,Japan
44554,11071249_4,_Tanaka_,_Kousei_,JAPANESE,M,Japan
44555,12828613_4,_Tanaka_,_Kyoko_,JAPANESE,F,Japan
44556,19073144_1,_Tanaka_,_Kenji_,JAPANESE,M,Japan
44557,8449402_2,_Tanaka_,_keiji_,JAPANESE,M,Japan
44558,10671491_5,_Tanaka_,_keiji_,JAPANESE,M,Japan
44559,18283803_5,_Tanaka_,_Kei_,JAPANESE,-,Japan
44560,8913105_4,_Tanaka_,_kiyoshi_,JAPANESE,M,Japan
44561,6678271_2,_Sasaki_,_takashi_,JAPANESE,M,Japan
44562,3097163_3,_Sasaki_,_toyoshi_,JAPANESE,M,Japan
44563,3800425_1,_Sasaki_,_tetsuo_,JAPANESE,M,Japan
44564,9714755_2,_Sasaki_,_takayo_,JAPANESE,F,Japan
44565,7880090_2,_Haddad_,_may_,ARAB,-,SaudiArabia
44566,16865091_1,_Haddad_,_Marianne_,FRENCH,F,France

In [2]:
#combine first_name and last_name
name_series = ethnea_df['Last'] + ethnea_df['First']
name_series = name_series.replace('_',' ',regex=True)
name_series = name_series.str.strip()
name_series = name_series.str.upper()

#extract ethnicity rows
ethnic_series = ethnea_df.Ethnea.values

In [4]:
# assume ethnic is a document
ethnic_dict = {}
for i,ethnic_i in enumerate(ethnic_series):
    if ethnic_i not in ethnic_dict:
        ethnic_dict[ethnic_i] = []
    # split the name
    split_name = name_series[i].split(' ')
    for name_j in split_name:
        if name_j!='':
            ethnic_dict[ethnic_i].append(name_j)

In [5]:
ethnic_keys = list(ethnic_dict.keys())

In [9]:
def transform_labels(x):
    y = np.zeros(len(ethnic_keys))
    y[ethnic_keys.index(x)]=1
    return y

labels = np.array(list(map(lambda x: transform_labels(x),ethnic_series)))

In [10]:
labels

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [13]:
from imblearn.over_sampling import SMOTE

ImportError: A sklearn version of at least 0.19.0 is required to use imbalanced-learn. 0.18.1 was found. Please upgrade sklearn

In [ ]:
with open(file='')